### ISSUE TITLE
Create Web Order.md - mismatch in fields.

### ISSUE THREAD

**Issue by CMartell-Bevica** [Bevica-SaaS/.github#4]
page 71977 "TVTWS API Web Order" has 56 fields.
The Create Web Order.md file 'Field Information' lists 87 fields.

Should 'Field information' list only the fields in the actual API?

**Comment by aconcato** [comment]
@CMartell-Bevica 

You are starting to like this github.. I was thinking we can use this portal for collaboration with "Partners" ?

**Comment by CMartell-Bevica** [comment]
@aconcato 
I only just able to open it, gimme time!

**Comment by aconcato** [comment]
In terms of answers, Yes only fields on the actual API page should be added to the documentation, probably at the very beginning we expose everything.
